[package]
name = "queryscheduler"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
good_lp = "1.14.2"
nats = "0.25.0"
petgraph = "0.8.3"
ractor = "0.15.10"
serde = "1.0.228"
surrealdb = "2.4.0"
tokio = "1.48.0"
uuid = "1.19.0"
